
services:
  app:
    container_name: chat_with_pdf_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - ./src/:/app/
    restart: always
    depends_on:
      - ollama
      - pgvector
    networks:
      - langnet

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    expose:
      - 11434
    volumes:
      - ./.ollama:/root/.ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - langnet

  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    networks:
      - langnet

volumes:
  pg_data:

networks:
  langnet: